### ISSUE TITLE
Blame & Compliment

### ISSUE THREAD

**Issue by ahdyt** [hadihammurabi/hamjs-query-builder#1]
Blame
1. When i install hamjs can it be interactive like when init an npm? like, which db driver i'll use? instead of manually install later, perhaps more be effective and efficient, and more code to write of course, frustating eh? hehe.
2. 
```  
As dialect you choose, it have to installed first.

    Example:

        npm install mysql for mysql
        npm install mysql2 for mysql2
        npm install mariadb for mariadb
        npm install pg for pg
```
plis dont disable above text in README.md, as it is dependency and it's important.

3. Inconsistency function/method naming, do u wanna use 3 digit or less or perhaps, full name? like prefer sel or select, del instead of delete, in over insert, and up over update. Make a standardize, every library/framework has their own stardardize, cause it's their own characteristic, remember "thinking in React?", like so.

Compliment
1. Write less, i dunno what happen under the hood, it's just do it, do the job.
2. Cool, tutorial, but need more explanation, wiki maybe?

**Comment by hadihammurabi** [comment]
Thank you for writing this issue.

1. I have plan to create CLI tools including driver selection i think.
Here, the [project](https://github.com/hadihammurabi/hamjs-query-builder/projects/2).
2. I have plan to create the docs using SSG (hugo) or something.
3. I have try to create a function with `delete` as name, but this is one of reserved keywords in Javacsript.
Then, i choose `del`, maybe change :rofl: 

For more issues, you can create another issue again.
Or you want to give me a PULL REQUEST? Yeahhh... The door is wide open :rofl:

**Comment by ahdyt** [comment]
Alright.
